import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

KITCHEN = Path(__file__).resolve().parent.parent / "bin" / "kitchen"

VALID_SKILL = textwrap.dedent("""\
    ---
    name: {name}
    description: "Do one thing well. Use when the fixture needs a valid skill."
    ---

    # {name}

    See [the reference](reference.md).
    """)


class KitchenFixture(unittest.TestCase):
    """A throwaway repo and HOME, so tests never touch the real setup."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name)
        self.repo = root / "repo"
        self.home = root / "home"
        (self.repo / "skills").mkdir(parents=True)
        (self.repo / "bin").mkdir()
        shutil.copy(KITCHEN, self.repo / "bin" / "kitchen")
        shutil.copytree(KITCHEN.parent.parent / "lib", self.repo / "lib", ignore=shutil.ignore_patterns("__pycache__"))
        self.home.mkdir()
        subprocess.run(["git", "init", "-q", str(self.repo)], check=True)

    extra_env = {}

    def tearDown(self):
        self.tmp.cleanup()

    def add_skill(self, name, text=None, files=("reference.md",)):
        skill = self.repo / "skills" / name
        skill.mkdir(parents=True)
        (skill / "SKILL.md").write_text(text if text is not None else VALID_SKILL.format(name=name))
        for file in files:
            (skill / file).write_text("detail\n")
        return skill

    def write_generated_rules(self, path):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("<!-- Generated by `kitchen install` from somewhere. -->\n\n# Old rules\n")

    def kitchen(self, *args, denylist=None, cwd=None, env_extra=None):
        env = {**os.environ, "HOME": str(self.home), "KITCHEN_REPO": str(self.repo), **(env_extra or {})}
        env["KITCHEN_DENYLIST"] = str(denylist or self.home / "no-denylist.txt")
        env["KITCHEN_STATE"] = str(self.home / "state")
        env["KITCHEN_CONFIG"] = str(self.home / "config")
        env.update(self.extra_env)
        return subprocess.run([sys.executable, str(KITCHEN), *args], env=env, capture_output=True, text=True, cwd=cwd)


class InstallTests(KitchenFixture):
    def test_install_links_each_skill_into_claude_and_codex(self):
        skill = self.add_skill("alpha")

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        for target in (self.home / ".claude" / "skills" / "alpha", self.home / ".agents" / "skills" / "alpha"):
            self.assertTrue(target.is_symlink())
            self.assertEqual(target.resolve(), skill.resolve())

    def test_install_removes_the_chef_agent_an_older_install_linked_and_keeps_the_persons_own(self):
        old = self.repo.resolve() / "agents"  # where an older kitchen kept it (install linked resolved paths); gone now
        old.mkdir()
        (old / "chef.md").write_text("---\nname: chef\n---\n")
        (old / "chef.toml").write_text('name = "chef"\n')
        claude, codex = self.home / ".claude" / "agents", self.home / ".codex" / "agents"
        for folder, name in ((claude, "chef.md"), (codex, "chef.toml")):
            folder.mkdir(parents=True)
            (folder / name).symlink_to(old / name)
        (claude / "mine.md").write_text("---\nname: mine\n---\n")
        for name in ("chef.md", "chef.toml"):
            (old / name).unlink()
        old.rmdir()

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(sorted(p.name for p in claude.iterdir()), ["mine.md"])
        self.assertEqual(list(codex.iterdir()), [])

    def test_install_registers_no_agent_even_when_the_repo_has_a_definition(self):
        # Claude Code may delegate to any registered agent on its own; chef mode must start only when the owner asks
        (self.repo / "agents").mkdir()
        (self.repo / "agents" / "chef.md").write_text("---\nname: chef\n---\n")
        (self.repo / "agents" / "chef.toml").write_text('name = "chef"\n')

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse((self.home / ".claude" / "agents").exists())
        self.assertFalse((self.home / ".codex" / "agents").exists())

    def test_install_writes_no_global_rules(self):
        (self.repo / "PRINCIPLES.md").write_text("# Principles\n\n## 1. Prove it on the real thing (`prove`)\n\nDone means you saw it.\n")
        (self.repo / "global").mkdir()
        (self.repo / "global" / "AGENTS.md").write_text("# Rules\n")  # what an older install would have written out

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse((self.home / ".claude" / "CLAUDE.md").exists())
        self.assertFalse((self.home / ".codex" / "AGENTS.md").exists())

    def test_install_moves_a_rules_file_an_older_install_wrote_aside_and_keeps_the_persons_own(self):
        old = self.home / ".claude" / "CLAUDE.md"
        self.write_generated_rules(old)
        mine = self.home / ".codex" / "AGENTS.md"
        mine.parent.mkdir(parents=True)
        mine.write_text("# My own rules\n")

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse(old.exists())
        backups = list((self.home / ".kitchen-backups").rglob("CLAUDE.md"))
        self.assertEqual([b.read_text().splitlines()[-1] for b in backups], ["# Old rules"])
        self.assertIn("the kitchen no longer writes your agent rules", result.stdout)
        self.assertEqual(mine.read_text(), "# My own rules\n")

    def test_install_moves_the_old_link_to_global_rules_aside(self):
        (self.repo / "global").mkdir()
        rules = self.repo / "global" / "AGENTS.md"
        rules.write_text("# Rules\n")
        old = self.home / ".claude" / "CLAUDE.md"
        old.parent.mkdir(parents=True)
        old.symlink_to(rules.resolve())  # the oldest install linked the resolved path

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse(old.is_symlink() or old.exists())
        self.assertEqual(rules.read_text(), "# Rules\n")

    def test_install_moves_rules_linked_from_another_clone_aside(self):
        other = Path(self.tmp.name) / "old-clone"
        (other / "global").mkdir(parents=True)
        (other / "bin").mkdir()
        (other / "bin" / "kitchen").write_text("#!/bin/sh\n")
        (other / "global" / "AGENTS.md").write_text("# Rules\n")
        generated = Path(self.tmp.name) / "elsewhere.md"
        self.write_generated_rules(generated)
        claude, codex = self.home / ".claude" / "CLAUDE.md", self.home / ".codex" / "AGENTS.md"
        for link, target in ((claude, other / "global" / "AGENTS.md"), (codex, generated)):
            link.parent.mkdir(parents=True)
            link.symlink_to(target)

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse(claude.is_symlink() or claude.exists())
        self.assertFalse(codex.is_symlink() or codex.exists())
        self.assertEqual((other / "global" / "AGENTS.md").read_text(), "# Rules\n")

    def test_install_keeps_a_link_to_the_persons_own_rules(self):
        mine = Path(self.tmp.name) / "my-rules.md"
        mine.write_text("# Mine\n")
        link = self.home / ".claude" / "CLAUDE.md"
        link.parent.mkdir(parents=True)
        link.symlink_to(mine)

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(link.resolve(), mine.resolve())

    def test_install_moves_the_old_rules_choice_aside(self):
        choice = self.home / "config" / "rules.txt"
        choice.parent.mkdir(parents=True)
        choice.write_text("global\n")

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse(choice.exists())
        self.assertEqual([b.read_text() for b in (self.home / ".kitchen-backups").rglob("rules.txt")], ["global\n"])

    def test_install_refuses_unmanaged_paths_and_changes_nothing(self):
        self.add_skill("alpha")
        self.add_skill("beta")
        existing = self.home / ".agents" / "skills" / "beta"
        existing.mkdir(parents=True)
        (existing / "SKILL.md").write_text("my own beta\n")

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 1)
        self.assertIn(str(existing), result.stdout)
        self.assertEqual((existing / "SKILL.md").read_text(), "my own beta\n")
        self.assertFalse((self.home / ".claude" / "skills" / "alpha").exists())

    def test_install_backup_moves_unmanaged_paths_before_linking(self):
        self.add_skill("beta")
        existing = self.home / ".agents" / "skills" / "beta"
        existing.mkdir(parents=True)
        (existing / "SKILL.md").write_text("my own beta\n")

        result = self.kitchen("install", "--backup")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(existing.is_symlink())
        backups = list((self.home / ".kitchen-backups").rglob("SKILL.md"))
        self.assertEqual([b.read_text() for b in backups], ["my own beta\n"])

    def test_install_removes_links_of_deleted_skills_but_keeps_foreign_skills(self):
        self.add_skill("alpha")
        self.kitchen("install")
        foreign = self.home / ".claude" / "skills" / "mine"
        foreign.mkdir()
        (self.repo / "skills" / "alpha" / "SKILL.md").unlink()

        result = self.kitchen("install")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse((self.home / ".claude" / "skills" / "alpha").is_symlink())
        self.assertTrue(foreign.is_dir())

    def test_install_puts_the_cli_on_the_user_bin(self):
        result = self.kitchen("install")

        link = self.home / ".local" / "bin" / "kitchen"
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(link.is_symlink())
        self.assertEqual(link.resolve(), (self.repo / "bin" / "kitchen").resolve())

    def test_install_is_idempotent(self):
        self.add_skill("alpha")
        self.kitchen("install")

        second = self.kitchen("install")

        self.assertEqual(second.returncode, 0)
        self.assertNotIn("linked", second.stdout)


class DoctorTests(KitchenFixture):
    def test_doctor_fails_until_install_then_passes(self):
        self.add_skill("alpha")

        before = self.kitchen("doctor")
        self.kitchen("install")
        after = self.kitchen("doctor")

        self.assertEqual(before.returncode, 1)
        self.assertIn("missing link", before.stdout)
        self.assertEqual(after.returncode, 0, after.stdout)

    def test_doctor_reports_a_link_whose_skill_lost_its_manifest(self):
        skill = self.add_skill("alpha")
        self.kitchen("install")
        (skill / "SKILL.md").rename(skill / "MOVED.md")

        result = self.kitchen("doctor")

        self.assertEqual(result.returncode, 1)
        self.assertIn("stale link", result.stdout)

    def test_doctor_reports_a_link_whose_source_was_deleted(self):
        skill = self.add_skill("alpha")
        self.kitchen("install")
        for file in skill.iterdir():
            file.unlink()
        skill.rmdir()

        result = self.kitchen("doctor")

        self.assertEqual(result.returncode, 1)
        self.assertIn("dangling link", result.stdout)

    def test_doctor_fails_on_a_rules_file_an_older_install_left_until_install_moves_it(self):
        self.write_generated_rules(self.home / ".codex" / "AGENTS.md")

        before = self.kitchen("doctor")
        self.kitchen("install")
        after = self.kitchen("doctor")

        self.assertEqual(before.returncode, 1)
        self.assertIn("written by an older kitchen install", before.stdout)
        self.assertEqual(after.returncode, 0, after.stdout)

    def test_doctor_lists_unmanaged_skills(self):
        self.kitchen("install")
        (self.home / ".agents" / "skills" / "mine").mkdir(parents=True)

        result = self.kitchen("doctor")

        self.assertIn("INFO  not managed by kitchen", result.stdout)


class LintTests(KitchenFixture):
    def lint(self):
        return self.kitchen("check", "--lint-only")

    def test_valid_skill_passes(self):
        self.add_skill("alpha")

        result = self.kitchen("check", "--lint-only", "--skills-dir", str(self.repo / "skills"))  # a project's skills may trigger on their own

        self.assertEqual(result.returncode, 0, result.stdout)

    def test_name_must_match_directory(self):
        self.add_skill("alpha", VALID_SKILL.format(name="beta"))

        self.assertIn("must equal the directory name", self.lint().stdout)

    def test_description_is_required(self):
        self.add_skill("alpha", "---\nname: alpha\n---\n\n# alpha\n")

        self.assertIn("description is required", self.lint().stdout)

    def test_block_scalar_description_is_rejected(self):
        self.add_skill("alpha", "---\nname: alpha\ndescription: >\n  folded\n---\n")

        self.assertIn("block scalar", self.lint().stdout)

    def test_skill_over_the_line_cap_fails(self):
        self.add_skill("alpha", VALID_SKILL.format(name="alpha") + "line\n" * 200)

        self.assertIn("lines (max 150)", self.lint().stdout)

    def test_broken_relative_link_fails(self):
        self.add_skill("alpha", files=())

        self.assertIn("broken link reference.md", self.lint().stdout)


class RedactionTests(unittest.TestCase):
    """`kitchen.transcripts.scrub` is an API: the automation imports it to redact issue logs."""

    def scrub(self, text):
        sys.path.insert(0, str(KITCHEN.parent.parent / "lib"))
        try:
            from kitchen.transcripts import scrub
        finally:
            sys.path.pop(0)
        return scrub(text)

    def test_quoted_json_keys_lose_their_values(self):
        value = "synthetic-" + "review-secret"
        text = '{"pass' + f'word": "{value}", "api' + f'Key":"{value}", "tok' + f'en": "{value}", "user": "ana"}}'

        scrubbed = self.scrub(text)

        self.assertNotIn(value, scrubbed)
        self.assertIn('"user": "ana"', scrubbed)

    def test_a_whole_pem_block_is_redacted(self):
        body = "MIIEsynthetic" + "KeyBody" * 6
        block = "-----BEGIN " + "RSA PRIVATE KEY-----\n" + body + "\n" + body[::-1] + "\n-----END " + "RSA PRIVATE KEY-----"

        scrubbed = self.scrub(f"before\n{block}\nafter")

        self.assertEqual(scrubbed, "before\n[REDACTED]\nafter")

    def test_a_truncated_pem_block_is_redacted_to_the_end(self):
        body = "MIIEsynthetic" + "KeyBody" * 6
        scrubbed = self.scrub("log:\n-----BEGIN " + "PRIVATE KEY-----\n" + body + "\n")

        self.assertNotIn(body, scrubbed)


class CheckRunsTestsHermeticallyTests(KitchenFixture):
    def test_tests_never_inherit_the_git_variables_a_hook_exports(self):
        (self.repo / "tests").mkdir()
        (self.repo / "tests" / "__init__.py").write_text("")
        (self.repo / "tests" / "test_env.py").write_text(textwrap.dedent("""\
            import os
            import unittest


            class Env(unittest.TestCase):
                def test_no_git_variables(self):
                    self.assertEqual([k for k in os.environ if k.startswith("GIT_")], [])
            """))
        hook_env = {"GIT_INDEX_FILE": str(self.repo / ".git" / "index"), "GIT_DIR": str(self.repo / ".git")}

        result = self.kitchen("check", env_extra=hook_env)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


class InvocationParityTests(KitchenFixture):
    MANUAL = VALID_SKILL.replace('description:', 'disable-model-invocation: true\ndescription:')

    def add_codex_policy(self, skill, allow):
        (skill / "agents").mkdir()
        (skill / "agents" / "openai.yaml").write_text(f"policy:\n  allow_implicit_invocation: {allow}\n")

    def test_manual_in_both_tools_passes(self):
        skill = self.add_skill("alpha", self.MANUAL.format(name="alpha"))
        self.add_codex_policy(skill, "false")

        result = self.kitchen("check", "--lint-only")

        self.assertEqual(result.returncode, 0, result.stdout)

    def test_manual_only_in_claude_fails(self):
        self.add_skill("alpha", self.MANUAL.format(name="alpha"))

        self.assertIn("manual-only for Claude but not for Codex", self.kitchen("check", "--lint-only").stdout)

    def test_a_kitchen_skill_that_triggers_on_its_own_fails(self):
        self.add_skill("alpha")

        result = self.kitchen("check", "--lint-only")

        self.assertEqual(result.returncode, 1)
        self.assertIn("alpha: every kitchen skill is manual-only", result.stdout)

    def test_manual_only_in_codex_fails(self):
        skill = self.add_skill("alpha")
        self.add_codex_policy(skill, "false")

        self.assertIn("manual-only for Codex but not for Claude", self.kitchen("check", "--lint-only").stdout)


class PublicSafetyTests(KitchenFixture):
    def test_personal_absolute_path_fails(self):
        self.add_skill("alpha")
        (self.repo / "notes.md").write_text("see /" + "Users/someone/project\n")

        result = self.lint()

        self.assertEqual(result.returncode, 1)
        self.assertIn("notes.md:1: personal path", result.stdout)

    def denylisted(self, terms, content):
        denylist = self.home / "denylist.txt"
        denylist.write_text("# clients\n" + "\n".join(terms) + "\n")
        (self.repo / "notes.md").write_text(content)
        return self.kitchen("check", "--lint-only", denylist=denylist)

    def test_lowercase_term_matches_any_case(self):
        result = self.denylisted(["acmecorp"], "built for AcmeCorp\n")

        self.assertEqual(result.returncode, 1)
        self.assertIn("notes.md:1: private term", result.stdout)

    def test_capitalized_term_matches_only_the_exact_name(self):
        flagged = self.denylisted(["Kestrel"], "built for Kestrel\n")
        common_word = self.denylisted(["Kestrel"], "a kestrel flew by\n")

        self.assertEqual(flagged.returncode, 1)
        self.assertEqual(common_word.returncode, 0, common_word.stdout)

    def test_term_inside_a_longer_word_is_not_flagged(self):
        result = self.denylisted(["novus"], "a novusual word\n")

        self.assertEqual(result.returncode, 0, result.stdout)

    def staged(self, name, content):
        path = self.repo / name
        path.write_text(content)
        subprocess.run(["git", "-C", str(self.repo), "add", "--", name], check=True)
        return path

    def test_secret_staged_then_removed_from_the_working_file_fails(self):
        token = "gh" + "p_" + "A1b2C3d4" * 5
        notes = self.staged("café notes.md", f"key {token}\n")
        notes.write_text("clean now\n")

        result = self.lint()

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("café notes.md (staged):1: GitHub token", result.stdout)

    def test_staged_blob_equal_to_the_working_file_is_reported_once(self):
        self.staged("notes.md", "see /" + "Users/someone/project\n")

        result = self.lint()

        self.assertEqual(result.stdout.count("personal path"), 1, result.stdout)

    def test_each_credential_shape_fails(self):
        samples = {
            "GitHub token": "gh" + "s_" + "x" * 36,
            "Slack token": "xo" + "xb-" + "1234567890-abcdef",
            "AWS access key": "AK" + "IA" + "ABCDEFGHIJKLMNOP",
            "API key": "s" + "k-proj-" + "q" * 32,
            "JWT": ".".join(["ey" + "J" + "h" * 16, "ey" + "J" + "p" * 16, "s" * 20]),
            "private key": "-----BEGIN " + "OPENSSH PRIVATE" + " KEY-----",
            "credential assignment": "pass" + 'word = "' + "hunter2hunter" + '"',
        }
        for label, sample in samples.items():
            with self.subTest(label):
                (self.repo / "notes.md").write_text(f"x {sample}\n")

                result = self.lint()

                self.assertIn(f"notes.md:1: {label} in a public repo", result.stdout)

    def test_staged_json_and_yaml_secrets_with_quoted_keys_fail(self):
        value = "synthetic-" + "review-secret"
        samples = [
            '{"pass' + f'word":"{value}"}}',
            '{"api' + f'Key": "{value}"}}',
            "{'client" + f"_secret': '{value}'}}",
            '"tok' + f'en": "{value}",',
            '"github' + f'_token" = "{value}"',
        ]
        for number, sample in enumerate(samples):
            with self.subTest(sample[:12]):
                self.staged(f"config{number}.json", sample + "\n")

                result = self.lint()

                self.assertIn(f"config{number}.json:1: credential assignment in a public repo", result.stdout)

    def test_quoted_placeholders_are_not_credentials(self):
        (self.repo / "notes.json").write_text('{"pass' + 'word": "", "tok' + 'en": "<redacted>", "secret": "${SECRET}"}\n')

        result = self.lint()

        self.assertEqual(result.returncode, 0, result.stdout)

    def test_placeholders_and_lookups_are_not_credentials(self):
        (self.repo / "notes.md").write_text("pass" + "word: <redacted>\napi_key = $API_KEY\nsecret = os.environ[\"X\"]\n")

        result = self.lint()

        self.assertEqual(result.returncode, 0, result.stdout)

    def test_missing_denylist_is_reported_not_silently_skipped(self):
        result = self.lint()

        self.assertIn("WARN  private-term scan skipped", result.stdout)

    def lint(self):
        return self.kitchen("check", "--lint-only")


if __name__ == "__main__":
    unittest.main()
