#!/usr/bin/env node

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseSkillFrontmatter } from "./lib/parse-skill-frontmatter.mjs";

const root = process.cwd();
const checkOnly = process.argv.includes("--check");

async function readCollection(collection) {
  const directory = path.join(root, collection);
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") {
      return [];
    }
    throw error;
  }

  const skills = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) {
      continue;
    }
    const location = `${collection}/${entry.name}/SKILL.md`;
    const source = await readFile(path.join(root, location), "utf8");
    const frontmatter = parseSkillFrontmatter(source, location);
    const tags = String(frontmatter.metadata?.tags ?? "")
      .split(",")
      .map((tag) => tag.trim())
      .filter(Boolean);
    skills.push({
      name: frontmatter.name,
      description: frontmatter.description,
      tags: [...new Set(tags)].sort(),
    });
  }
  return skills.sort((left, right) => left.name.localeCompare(right.name));
}

function escapeTable(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function renderTopics(skills, collection) {
  const topics = new Map();
  for (const skill of skills) {
    for (const tag of skill.tags) {
      const names = topics.get(tag) ?? [];
      names.push(skill.name);
      topics.set(tag, names);
    }
  }
  if (topics.size === 0) {
    return "";
  }

  const lines = ["## Topics", ""];
  for (const tag of [...topics.keys()].sort()) {
    lines.push(`### ${tag}`, "");
    for (const name of topics.get(tag).sort()) {
      lines.push(`- [${name}](${collection}/${name}/SKILL.md)`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function renderStable(skills) {
  const lines = [
    "<!-- Generated by npm run catalog. Do not edit directly. -->",
    "# Stable Skills",
    "",
    "These skills have passed the portable Codex and Claude Code promotion gate.",
    "",
  ];
  if (skills.length === 0) {
    lines.push("No stable skills have been published yet.");
    return `${lines.join("\n")}\n`;
  }

  lines.push(
    "| Skill | Description | Tags | Global install |",
    "| --- | --- | --- | --- |",
  );
  for (const skill of skills) {
    lines.push(
      `| [${skill.name}](skills/${skill.name}/SKILL.md) | ${escapeTable(skill.description)} | ${skill.tags.map((tag) => `\`${tag}\``).join(", ")} | \`npx skills add SantanaJcp/agent-skills@${skill.name} -g -a codex -a claude-code\` |`,
    );
  }
  lines.push("", renderTopics(skills, "skills"));
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderIncubator(skills) {
  const lines = [
    "<!-- Generated by npm run catalog. Do not edit directly. -->",
    "# Incubator",
    "",
    "Incubator skills are experimental and are not covered by the stable compatibility promise.",
    "",
  ];
  if (skills.length === 0) {
    lines.push("No skills are currently incubating.");
    return `${lines.join("\n")}\n`;
  }

  lines.push("| Skill | Description | Tags |", "| --- | --- | --- |");
  for (const skill of skills) {
    lines.push(
      `| [${skill.name}](incubator/${skill.name}/SKILL.md) | ${escapeTable(skill.description)} | ${skill.tags.map((tag) => `\`${tag}\``).join(", ")} |`,
    );
  }
  lines.push("", renderTopics(skills, "incubator"));
  return `${lines.join("\n").trimEnd()}\n`;
}

async function updateCatalog(fileName, content) {
  const target = path.join(root, fileName);
  if (!checkOnly) {
    await writeFile(target, content);
    return;
  }

  let existing = "";
  try {
    existing = await readFile(target, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") {
      throw error;
    }
  }
  if (existing !== content) {
    throw new Error(`${fileName} is stale. Run npm run catalog.`);
  }
}

const stable = await readCollection("skills");
const incubator = await readCollection("incubator");

try {
  await updateCatalog("CATALOG.md", renderStable(stable));
  await updateCatalog("INCUBATOR.md", renderIncubator(incubator));
} catch (error) {
  console.error(error.message);
  process.exit(1);
}

console.log(
  checkOnly
    ? "Catalogs are current."
    : "Generated CATALOG.md and INCUBATOR.md.",
);
