"""What older installs left in the person's global setup, and how `kitchen install` takes it back out.

The kitchen used to be always on: a generated rules file (~/.claude/CLAUDE.md, ~/.codex/AGENTS.md) and its guards as
PreToolUse hooks in ~/.claude/settings.json and ~/.codex/hooks.json, in every session and every repo. Now it is on only
in chef mode, and the guards live in each project (`kitchen guards`). `install` moves a generated rules file to the
backup folder, drops the kitchen's handlers from the hook files (every other key and hook stays), and `doctor` fails
while any of it is left. Principles: `owner-attention` (the kitchen runs only when called), `no-fallbacks` (a hook
file it cannot parse is refused, never rewritten blind), `isolate` (reruns change nothing).
"""
from __future__ import annotations

import copy
import json
import os
import shlex
import shutil
from dataclasses import dataclass
from pathlib import Path

MARKER = "<!-- Generated by `kitchen install`"
# The guards older installs merged. Recognized by name under any clone's hooks/: the install that wrote them may have
# run from another clone, or from a checkout that is gone.
OLD_GUARDS = ("deny-no-verify", "deny-recursive-rm", "deny-shared-push")


@dataclass
class HookFile:
    tool: str
    path: Path
    after: dict
    problem: str | None   # set when the file cannot be parsed


def generated(path: Path) -> bool:
    if not path.is_file():
        return False
    with path.open(encoding="utf-8", errors="replace") as handle:
        return handle.readline().startswith(MARKER)


def old_rules_link(target: Path, repo: Path) -> bool:
    """The oldest install linked a kitchen clone's global/AGENTS.md: this repo's, another clone's, or one now gone."""
    if target.is_relative_to(repo):
        return True
    clone = target.parent.parent
    return target.name == "AGENTS.md" and target.parent.name == "global" and \
        ((clone / "bin" / "kitchen").is_file() or not target.exists())


def rule_files(h: Path, repo: Path) -> list[Path]:
    """Global rule files an older install wrote: generated (first line is MARKER), directly or through a link, or a
    link to a kitchen clone's global/AGENTS.md."""
    found = []
    for path in (h / ".claude" / "CLAUDE.md", h / ".codex" / "AGENTS.md"):
        target = Path(os.path.normpath(path.parent / os.readlink(path))) if path.is_symlink() else None
        if generated(path) or (target is not None and old_rules_link(target, repo)):
            found.append(path)
    return found


def rules_choice(config: Path) -> Path | None:
    """The old `--rules` choice file; nothing reads it now."""
    path = config / "rules.txt"
    return path if path.is_file() else None


def is_kitchen_handler(handler, repo: Path) -> bool:
    """A handler an older install added: its command is one of the old guards in some kitchen clone's hooks/."""
    if not isinstance(handler, dict) or not isinstance(handler.get("command"), str):
        return False
    try:
        words = shlex.split(handler["command"])
    except ValueError:
        return False
    if not words:
        return False
    path = Path(os.path.normpath(words[0]))
    return path.is_absolute() and (path.parent == repo / "hooks" or (path.parent.name == "hooks" and path.name in OLD_GUARDS))


def load(path: Path) -> tuple[dict | None, str | None]:
    if not path.exists():
        return {}, None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        return None, f"not valid JSON ({error})"
    if not isinstance(data, dict):
        return None, "not a JSON object"
    hooks = data.get("hooks", {})
    if not isinstance(hooks, dict):
        return None, "`hooks` is not an object"
    groups = hooks.get("PreToolUse", [])
    if not isinstance(groups, list) or not all(isinstance(g, dict) and isinstance(g.get("hooks", []), list) for g in groups):
        return None, "`hooks.PreToolUse` is not a list of {matcher, hooks: [...]} groups"
    return data, None


def stripped(data: dict, repo: Path) -> dict:
    """data without the kitchen's handlers; a group they emptied goes too, nothing else changes."""
    result = copy.deepcopy(data)
    hooks = result.get("hooks", {})
    if "PreToolUse" not in hooks:
        return result
    groups = []
    for group in hooks["PreToolUse"]:
        kept = [h for h in group.get("hooks", []) if not is_kitchen_handler(h, repo)]
        if kept or not group.get("hooks"):
            groups.append({**group, "hooks": kept})
    if groups:
        result["hooks"] = {**hooks, "PreToolUse": groups}
    else:
        rest = {k: v for k, v in hooks.items() if k != "PreToolUse"}
        if rest:
            result["hooks"] = rest
        else:
            result.pop("hooks")
    return result


def hook_files(h: Path, repo: Path) -> list[HookFile]:
    """The global hook files that still hold kitchen handlers, or that cannot be read to tell."""
    found = []
    for tool, path in (("Claude Code", h / ".claude" / "settings.json"), ("Codex", h / ".codex" / "hooks.json")):
        before, problem = load(path)
        after = stripped(before, repo) if before is not None else {}
        if problem or before != after:
            found.append(HookFile(tool, path, after, problem and f"{path}: {problem}"))
    return found


def write_json(path: Path, data: dict) -> None:
    real = path.resolve() if path.is_symlink() else path
    tmp = real.with_name(f".{real.name}.kitchen-tmp")
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    shutil.copymode(real, tmp)
    os.replace(tmp, real)


def remove_hooks(files: list[HookFile]) -> list[str]:
    lines = []
    for file in files:
        assert file.problem is None, "install refuses a hook file it cannot parse"
        write_json(file.path, file.after)
        lines.append(f"removed    {file.tool}: the kitchen's global guards from {file.path} (guards now live in each project: kitchen guards <repo>)")
    return lines


def doctor(h: Path, repo: Path, config: Path) -> list[str]:
    """FAIL lines for whatever an older install left behind."""
    out = [f"{p} was written by an older kitchen install; run `kitchen install` to move it aside" for p in rule_files(h, repo)]
    for file in hook_files(h, repo):
        out.append(f"{file.problem}; fix it so `kitchen install` can remove the old kitchen guards" if file.problem else
                   f"{file.tool}: {file.path} still runs the kitchen's global guards; run `kitchen install` to remove them")
    if rules_choice(config):
        out.append(f"{rules_choice(config)} is from an older install and nothing reads it; run `kitchen install` to move it aside")
    return out
