"""The global rules file each agent reads: the person's own rules, then the index of the kitchen's principles.

`kitchen install` writes it to ~/.claude/CLAUDE.md and ~/.codex/AGENTS.md. Codex reads one global file and has no
include, so the file is generated, not linked: edit the sources, then rerun `kitchen install`; `kitchen doctor`
fails while an installed copy differs from what install would write now.

Whose rules: `--rules <file>` (or `none`) at install, kept in ~/.config/kitchen/rules.txt. Without one, the
kitchen's own global/AGENTS.md, and install says so. Principles: `handoff` (every agent finds the principles),
`small-owned` (one index line per principle; the detail stays in PRINCIPLES.md).
"""
from __future__ import annotations

import re
from pathlib import Path

from kitchen import common

MARKER = "<!-- Generated by `kitchen install`"
HEADING = re.compile(r"^## \d+\. (?P<title>.+?) \(`(?P<id>[a-z-]+)`\)\s*$")


class RulesError(Exception):
    pass


def choice_path() -> Path:
    return common.config_dir() / "rules.txt"


def configured() -> str | None:
    """The saved choice: an absolute path, "none", or None when the person never chose."""
    path = choice_path()
    if not path.is_file():
        return None
    value = path.read_text(encoding="utf-8").strip()
    if not value:
        raise RulesError(f"{path} is empty: write an absolute path or `none` in it, or rerun `kitchen install --rules ...`")
    return value


def save(choice: str) -> None:
    path = choice_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(choice + "\n", encoding="utf-8")


def resolve(choice: str | None, repo: Path) -> Path | None:
    """The rules file for a choice; None means principles only. A chosen file that does not exist is an error."""
    if choice == "none":
        return None
    if choice in (None, "global"):
        default = repo / "global" / "AGENTS.md"
        return default if default.is_file() else None
    path = Path(choice).expanduser()
    if not path.is_absolute():
        raise RulesError(f"--rules takes an absolute path, `global` or `none`; got {choice!r}")
    if not path.is_file():
        raise RulesError(f"the rules file {path} does not exist")
    return path


def principles(repo: Path) -> list[tuple[str, str, str]]:
    """(id, title, first sentence) for each principle in PRINCIPLES.md, in order."""
    path = repo / "PRINCIPLES.md"
    if not path.is_file():
        return []
    lines = path.read_text(encoding="utf-8").splitlines()
    out = []
    for i, line in enumerate(lines):
        match = HEADING.match(line)
        if not match:
            continue
        body = next((l for l in lines[i + 1:] if l.strip()), "")
        sentence = re.split(r"(?<=[.!?])\s", body.strip(), maxsplit=1)[0]
        out.append((match["id"], match["title"], sentence))
    return out


def render(repo: Path, rules: Path | None) -> str | None:
    """The file to install, or None when there are neither rules nor principles."""
    index = principles(repo)
    if rules is None and not index:
        return None
    sources = " and ".join(str(p) for p in ([rules] if rules else []) + ([repo / "PRINCIPLES.md"] if index else []))
    parts = [f"{MARKER} from {sources}. Edit those, then rerun `kitchen install`. -->", ""]
    if rules:
        parts += [rules.read_text(encoding="utf-8").rstrip("\n"), ""]
    if index:
        parts += ["## Principles", "",
                  f"The why behind these rules is in {repo / 'PRINCIPLES.md'}. When no rule settles a decision, read it and decide the way it points.",
                  ""]
        parts += [f"- `{pid}`: {title}. {sentence}" for pid, title, sentence in index]
        parts.append("")
    return "\n".join(parts)


def generated(path: Path) -> bool:
    """A regular file this kitchen wrote: install may replace it; anything else is the person's."""
    if path.is_symlink() or not path.is_file():
        return False
    with path.open(encoding="utf-8", errors="replace") as handle:
        return handle.readline().startswith(MARKER)
